Author: Daniel Lillard

Date: 2026.03.23

Desc: Basic LSTM model here to predict stock prices on the smoothed data. This is a "worst possible" algorithm incase the clustering is not useful.

In [2]:
import pandas as pd

def convert_and_cut_date(df: pd.DataFrame, start_date: str, end_date: str) -> pd.DataFrame:
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df[df['timestamp'] >= start_date]
    df = df[df['timestamp'] <= end_date]
    return df

In [3]:
# smooth all data

def smooth_data(df: pd.DataFrame) -> pd.DataFrame:
    # smooth the data using a rolling window of 5 days
    raw_close = df.pivot(columns="ticker", values="close",index="timestamp")
    smoothed  = raw_close.rolling(window=5, min_periods=1).mean()

    
    
    return smoothed

In [4]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

def build_model(window: int) -> Sequential:
    # CNN-LSTM architecture from the paper.
    model = Sequential([
        Conv1D(filters=5, kernel_size=3, activation="relu",
               padding="same", input_shape=(window, 1)),
        Dropout(0.2),
        LSTM(128, return_sequences=True),
        Dropout(0.2),
        LSTM(64),
        Dropout(0.2),
        Dense(60, activation="relu"),
        Dense(1),
    ])
    model.compile(optimizer="adam", loss="mse")
    return model

In [37]:
# MAIN
import pandas as pd

TRAIN_START  = "2019-07-01"
TRAIN_END    = "2021-12-31"   # last training day before test window
TEST_START   = "2022-01-03"
TEST_END     = "2022-03-31"
 
WINDOW_SIZE  = 30             # number of past days used as input
EPOCHS       = 20
BATCH_SIZE   = 32

df = pd.read_csv("aa_daily_data.csv")

# for testing, only use 5 stocks
# df = df[df['ticker'].isin(['ACHC', 'AEE', 'HCKT', 'HALO', 'MA'])]

# for testing, only use 1 stocks
df = df[df['ticker'].isin(['UE'])]

df = convert_and_cut_date(df, TRAIN_START, TEST_END)

df_smoothed = smooth_data(df)

raw_open = df.pivot(columns='ticker',index='timestamp')['open']
raw_close = df.pivot(columns='ticker',index='timestamp')['close']

# # lets start with just one day to make sure the pipeline works
test_date = "2022-01-03"
# test_data = df[df['timestamp'] == test_date]

# train_data = df_smoothed[df_smoothed['timestamp'] < test_date]
# # only go back window size days from the test date to avoid data leakage
# train_data = train_data[train_data['timestamp'] >= (pd.to_datetime(test_date) - pd.Timedelta(days=WINDOW_SIZE))]


early_stop = EarlyStopping(monitor="loss", patience=3, restore_best_weights=True)

model = build_model(WINDOW_SIZE)

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [6]:
# Scale
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled = scaler.fit_transform(df_smoothed.values.reshape(-1, 1)).flatten()

In [7]:
import numpy as np

def build_sequences(series: np.ndarray, window: int):
    """
    Build (X, y) pairs from a 1D scaled series.
    X shape: (n_samples, window, 1)
    y shape: (n_samples)
    """
    X, y = [], []
    for i in range(window, len(series)):
        X.append(series[i - window:i])
        y.append(series[i])
    return np.array(X), np.array(y)

In [8]:
X, y = build_sequences(scaled, WINDOW_SIZE)
X    = X[..., np.newaxis]   # (n, window, 1)

In [9]:
tf.keras.backend.clear_session()
model = build_model(WINDOW_SIZE)
model.fit(X, y,
          epochs=EPOCHS,
          batch_size=BATCH_SIZE,
          callbacks=[early_stop],
          verbose=0)

# Predict
last_window = scaled[-WINDOW_SIZE:].reshape(1, WINDOW_SIZE, 1)
pred_scaled = model.predict(last_window, verbose=0)[0, 0]
pred_price  = scaler.inverse_transform([[pred_scaled]])[0, 0]

WARNING:tensorflow:From c:\file_struct\programs\python\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [10]:
opens = raw_open['HALO']

In [11]:
pred_price, opens.get(test_date, default=np.nan)

(np.float64(37.564398844957346), np.float64(39.8))

In [12]:
# ─────────────────────────────────────────────
# TRADING SIGNALS
# ─────────────────────────────────────────────
 
def trading_signal(prev_close: float, open_t: float, predicted: float) -> str:
    """
    Buy  if prev_close < predicted AND open_t < predicted
    Sell if prev_close > predicted AND open_t > predicted
    """
    if prev_close < predicted and open_t < predicted:
        return "BUY"
    elif prev_close > predicted and open_t > predicted:
        return "SELL"
    return "HOLD"
 
 
def compute_trade_return(signal: str, open_t: float, close_t: float) -> float:
    if signal == "BUY":
        return (close_t - open_t) / open_t
    elif signal == "SELL":
        return (open_t - close_t) / open_t
    return 0.0

In [13]:
test_date_small = "2022-01-03"

raw_close.loc[test_date_small]

ticker
HALO    41.06
Name: 2022-01-03 00:00:00, dtype: float64

In [39]:
ticker = "UE"

actual_close = raw_close.loc[test_date, ticker]
actual_open = raw_open.loc[test_date, ticker]
prev_close = raw_close.iloc[raw_close.index.get_loc(test_date) - 1][ticker]

signal      = trading_signal(prev_close, actual_open, pred_price)
trade_ret   = compute_trade_return(signal, actual_open, actual_close)

In [15]:
signal, trade_ret

('SELL', np.float64(-0.03165829145728656))

In [ ]:
df_smoothed[df_smoothed.index >= (pd.to_datetime('2022-01-03') - pd.Timedelta(days=WINDOW_SIZE))]

ticker        HALO
timestamp
2021-12-06  32.692
2021-12-07  32.586
2021-12-08  32.800
2021-12-09  32.528
2021-12-10  32.948
...            ...
2022-03-25  37.842
2022-03-28  38.236
2022-03-29  38.774
2022-03-30  39.302
2022-03-31  39.534

[81 rows x 1 columns]

In [21]:
train_data = df_smoothed[df_smoothed.index < test_date]

In [24]:
train_data

ticker           HALO
timestamp
2019-07-01  17.570000
2019-07-02  17.475000
2019-07-03  17.546667
2019-07-05  17.492500
2019-07-08  17.408000
...               ...
2022-03-24  37.688000
2022-03-25  37.842000
2022-03-28  38.236000
2022-03-29  38.774000
2022-03-30  39.302000

[694 rows x 1 columns]

In [36]:
df_smoothed

ticker           HALO
timestamp
2019-07-01  17.570000
2019-07-02  17.475000
2019-07-03  17.546667
2019-07-05  17.492500
2019-07-08  17.408000
...               ...
2022-03-25  37.842000
2022-03-28  38.236000
2022-03-29  38.774000
2022-03-30  39.302000
2022-03-31  39.534000

[695 rows x 1 columns]

In [42]:
# cool, now we have to move the window and retrain the model for each test day in the test window, 
# then compute signals and returns for each day.

for i, test_date in enumerate(pd.date_range(TEST_START, TEST_END)):
    # if there is a gap, error out
    if test_date not in raw_close.index:
        print(f"Date {test_date} not in data, skipping.")
        continue
    
    test_date = test_date.strftime("%Y-%m-%d")
    print(f"Testing on {test_date}...")
    
    # Prepare training data up to the day before the test date
    train_data = df_smoothed[df_smoothed.index < test_date]
    train_data = train_data[train_data.index <= (pd.to_datetime(test_date) - pd.Timedelta(days=WINDOW_SIZE))]
    
    if len(train_data) < WINDOW_SIZE:
        print("Not enough training data, skipping this date.")
        print(train_data)
        continue
    
    # Scale
    scaled = scaler.fit_transform(train_data.values.reshape(-1, 1)).flatten()
    
    # Build sequences
    X, y = build_sequences(scaled, WINDOW_SIZE)
    X = X[..., np.newaxis]
    
    # Train model
    tf.keras.backend.clear_session()
    model = build_model(WINDOW_SIZE)
    model.fit(X, y,
              epochs=EPOCHS,
              batch_size=BATCH_SIZE,
              callbacks=[early_stop],
              verbose=0)
    
    # Predict
    last_window = scaled[-WINDOW_SIZE:].reshape(1, WINDOW_SIZE, 1)
    pred_scaled = model.predict(last_window, verbose=0)[0, 0]
    pred_price  = scaler.inverse_transform([[pred_scaled]])[0, 0]
    
    # Compute signal and return
    actual_close = raw_close.loc[test_date, ticker]
    actual_open = raw_open.loc[test_date, ticker]
    prev_close = raw_close.iloc[raw_close.index.get_loc(test_date) - 1][ticker]

    signal      = trading_signal(prev_close, actual_open, pred_price)
    trade_ret   = compute_trade_return(signal, actual_open, actual_close)
    
    print(f"Predicted: {pred_price:.2f}, Previous Close: {prev_close:.2f}, Actual Open: {actual_open:.2f}, Actual Close: {actual_close:.2f}, Signal: {signal}, Return: {trade_ret:.4f}\n")

Testing on 2022-01-03...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.50, Previous Close: 19.00,Actual Open: 19.06, Actual Close: 19.21, Signal: SELL, Return: -0.0079

Testing on 2022-01-04...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.83, Previous Close: 19.21,Actual Open: 19.41, Actual Close: 19.61, Signal: SELL, Return: -0.0103

Testing on 2022-01-05...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.88, Previous Close: 19.61,Actual Open: 19.71, Actual Close: 19.35, Signal: SELL, Return: 0.0183

Testing on 2022-01-06...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.24, Previous Close: 19.35,Actual Open: 19.58, Actual Close: 19.42, Signal: SELL, Return: 0.0082

Testing on 2022-01-07...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.35, Previous Close: 19.42,Actual Open: 19.36, Actual Close: 19.52, Signal: SELL, Return: -0.0083

Date 2022-01-08 00:00:00 not in data, skipping.
Date 2022-01-09 00:00:00 not in data, skipping.
Testing on 2022-01-10...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.10, Previous Close: 19.52,Actual Open: 19.49, Actual Close: 19.51, Signal: SELL, Return: -0.0010

Testing on 2022-01-11...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.83, Previous Close: 19.51,Actual Open: 19.55, Actual Close: 19.47, Signal: SELL, Return: 0.0041

Testing on 2022-01-12...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.26, Previous Close: 19.47,Actual Open: 19.48, Actual Close: 19.42, Signal: SELL, Return: 0.0031

Testing on 2022-01-13...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 16.46, Previous Close: 19.42,Actual Open: 19.59, Actual Close: 19.76, Signal: SELL, Return: -0.0087

Testing on 2022-01-14...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 16.39, Previous Close: 19.76,Actual Open: 19.61, Actual Close: 19.48, Signal: SELL, Return: 0.0066

Date 2022-01-15 00:00:00 not in data, skipping.
Date 2022-01-16 00:00:00 not in data, skipping.
Date 2022-01-17 00:00:00 not in data, skipping.
Testing on 2022-01-18...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 16.86, Previous Close: 19.48,Actual Open: 19.30, Actual Close: 19.16, Signal: SELL, Return: 0.0073

Testing on 2022-01-19...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 15.01, Previous Close: 19.16,Actual Open: 19.18, Actual Close: 18.69, Signal: SELL, Return: 0.0255

Testing on 2022-01-20...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.36, Previous Close: 18.69,Actual Open: 18.65, Actual Close: 18.22, Signal: SELL, Return: 0.0231

Testing on 2022-01-21...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.77, Previous Close: 18.22,Actual Open: 18.21, Actual Close: 18.20, Signal: SELL, Return: 0.0005

Date 2022-01-22 00:00:00 not in data, skipping.
Date 2022-01-23 00:00:00 not in data, skipping.
Testing on 2022-01-24...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.46, Previous Close: 18.20,Actual Open: 17.92, Actual Close: 18.29, Signal: BUY, Return: 0.0206

Testing on 2022-01-25...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.20, Previous Close: 18.29,Actual Open: 18.02, Actual Close: 18.30, Signal: BUY, Return: 0.0155

Testing on 2022-01-26...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.60, Previous Close: 18.30,Actual Open: 18.45, Actual Close: 18.16, Signal: BUY, Return: -0.0157

Testing on 2022-01-27...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.30, Previous Close: 18.16,Actual Open: 18.25, Actual Close: 17.88, Signal: BUY, Return: -0.0203

Testing on 2022-01-28...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.70, Previous Close: 17.88,Actual Open: 17.82, Actual Close: 18.39, Signal: BUY, Return: 0.0320

Date 2022-01-29 00:00:00 not in data, skipping.
Date 2022-01-30 00:00:00 not in data, skipping.
Testing on 2022-01-31...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.96, Previous Close: 18.39,Actual Open: 18.18, Actual Close: 18.24, Signal: BUY, Return: 0.0033

Testing on 2022-02-01...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.50, Previous Close: 18.24,Actual Open: 18.17, Actual Close: 18.11, Signal: SELL, Return: 0.0033

Testing on 2022-02-02...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.63, Previous Close: 18.11,Actual Open: 18.04, Actual Close: 18.31, Signal: BUY, Return: 0.0150

Testing on 2022-02-03...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.10, Previous Close: 18.31,Actual Open: 18.18, Actual Close: 17.95, Signal: SELL, Return: 0.0127

Testing on 2022-02-04...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.17, Previous Close: 17.95,Actual Open: 17.69, Actual Close: 17.64, Signal: SELL, Return: 0.0028

Date 2022-02-05 00:00:00 not in data, skipping.
Date 2022-02-06 00:00:00 not in data, skipping.
Testing on 2022-02-07...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.50, Previous Close: 17.64,Actual Open: 17.67, Actual Close: 17.60, Signal: BUY, Return: -0.0040

Testing on 2022-02-08...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.34, Previous Close: 17.60,Actual Open: 17.56, Actual Close: 17.66, Signal: BUY, Return: 0.0057

Testing on 2022-02-09...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.17, Previous Close: 17.66,Actual Open: 17.81, Actual Close: 17.94, Signal: BUY, Return: 0.0073

Testing on 2022-02-10...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.74, Previous Close: 17.94,Actual Open: 17.61, Actual Close: 17.69, Signal: BUY, Return: 0.0045

Testing on 2022-02-11...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 15.54, Previous Close: 17.69,Actual Open: 17.75, Actual Close: 17.56, Signal: SELL, Return: 0.0107

Date 2022-02-12 00:00:00 not in data, skipping.
Date 2022-02-13 00:00:00 not in data, skipping.
Testing on 2022-02-14...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.29, Previous Close: 17.56,Actual Open: 17.57, Actual Close: 17.32, Signal: BUY, Return: -0.0142

Testing on 2022-02-15...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.19, Previous Close: 17.32,Actual Open: 17.52, Actual Close: 17.49, Signal: BUY, Return: -0.0017

Testing on 2022-02-16...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.07, Previous Close: 17.49,Actual Open: 18.71, Actual Close: 18.67, Signal: BUY, Return: -0.0021

Testing on 2022-02-17...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.11, Previous Close: 18.67,Actual Open: 18.39, Actual Close: 18.31, Signal: SELL, Return: 0.0044

Testing on 2022-02-18...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.87, Previous Close: 18.31,Actual Open: 18.19, Actual Close: 18.14, Signal: BUY, Return: -0.0027

Date 2022-02-19 00:00:00 not in data, skipping.
Date 2022-02-20 00:00:00 not in data, skipping.
Date 2022-02-21 00:00:00 not in data, skipping.
Testing on 2022-02-22...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.07, Previous Close: 18.14,Actual Open: 18.09, Actual Close: 18.05, Signal: SELL, Return: 0.0022

Testing on 2022-02-23...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.77, Previous Close: 18.05,Actual Open: 18.19, Actual Close: 17.64, Signal: BUY, Return: -0.0302

Testing on 2022-02-24...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.83, Previous Close: 17.64,Actual Open: 17.24, Actual Close: 18.06, Signal: BUY, Return: 0.0476

Testing on 2022-02-25...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.08, Previous Close: 18.06,Actual Open: 18.19, Actual Close: 18.52, Signal: HOLD, Return: 0.0000

Date 2022-02-26 00:00:00 not in data, skipping.
Date 2022-02-27 00:00:00 not in data, skipping.
Testing on 2022-02-28...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.82, Previous Close: 18.52,Actual Open: 18.18, Actual Close: 18.22, Signal: BUY, Return: 0.0022

Testing on 2022-03-01...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.33, Previous Close: 18.22,Actual Open: 18.18, Actual Close: 17.98, Signal: BUY, Return: -0.0110

Testing on 2022-03-02...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.09, Previous Close: 17.98,Actual Open: 18.12, Actual Close: 18.38, Signal: BUY, Return: 0.0143

Testing on 2022-03-03...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.85, Previous Close: 18.38,Actual Open: 18.54, Actual Close: 18.59, Signal: BUY, Return: 0.0027

Testing on 2022-03-04...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.48, Previous Close: 18.59,Actual Open: 18.39, Actual Close: 18.53, Signal: BUY, Return: 0.0076

Date 2022-03-05 00:00:00 not in data, skipping.
Date 2022-03-06 00:00:00 not in data, skipping.
Testing on 2022-03-07...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.30, Previous Close: 18.53,Actual Open: 18.56, Actual Close: 18.05, Signal: SELL, Return: 0.0275

Testing on 2022-03-08...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.04, Previous Close: 18.05,Actual Open: 18.16, Actual Close: 18.58, Signal: SELL, Return: -0.0231

Testing on 2022-03-09...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.87, Previous Close: 18.58,Actual Open: 18.81, Actual Close: 18.53, Signal: BUY, Return: -0.0149

Testing on 2022-03-10...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.81, Previous Close: 18.53,Actual Open: 18.25, Actual Close: 18.40, Signal: SELL, Return: -0.0082

Testing on 2022-03-11...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 16.59, Previous Close: 18.40,Actual Open: 18.51, Actual Close: 18.36, Signal: SELL, Return: 0.0081

Date 2022-03-12 00:00:00 not in data, skipping.
Date 2022-03-13 00:00:00 not in data, skipping.
Testing on 2022-03-14...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.93, Previous Close: 18.36,Actual Open: 18.33, Actual Close: 18.15, Signal: BUY, Return: -0.0098

Testing on 2022-03-15...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.34, Previous Close: 18.15,Actual Open: 18.37, Actual Close: 18.42, Signal: SELL, Return: -0.0027

Testing on 2022-03-16...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.56, Previous Close: 18.42,Actual Open: 18.68, Actual Close: 18.69, Signal: BUY, Return: 0.0005

Testing on 2022-03-17...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.26, Previous Close: 18.69,Actual Open: 18.59, Actual Close: 18.64, Signal: BUY, Return: 0.0027

Testing on 2022-03-18...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.70, Previous Close: 18.64,Actual Open: 18.69, Actual Close: 18.87, Signal: SELL, Return: -0.0096

Date 2022-03-19 00:00:00 not in data, skipping.
Date 2022-03-20 00:00:00 not in data, skipping.
Testing on 2022-03-21...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 14.36, Previous Close: 18.87,Actual Open: 18.91, Actual Close: 18.87, Signal: SELL, Return: 0.0021

Testing on 2022-03-22...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.06, Previous Close: 18.87,Actual Open: 19.06, Actual Close: 19.05, Signal: BUY, Return: -0.0005

Testing on 2022-03-23...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.01, Previous Close: 19.05,Actual Open: 18.95, Actual Close: 18.74, Signal: SELL, Return: 0.0111

Testing on 2022-03-24...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.49, Previous Close: 18.74,Actual Open: 18.79, Actual Close: 18.53, Signal: SELL, Return: 0.0138

Testing on 2022-03-25...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 15.24, Previous Close: 18.53,Actual Open: 18.52, Actual Close: 18.92, Signal: SELL, Return: -0.0216

Date 2022-03-26 00:00:00 not in data, skipping.
Date 2022-03-27 00:00:00 not in data, skipping.
Testing on 2022-03-28...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 15.45, Previous Close: 18.92,Actual Open: 18.93, Actual Close: 18.90, Signal: SELL, Return: 0.0016

Testing on 2022-03-29...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 17.72, Previous Close: 18.90,Actual Open: 19.16, Actual Close: 19.56, Signal: SELL, Return: -0.0209

Testing on 2022-03-30...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 18.23, Previous Close: 19.56,Actual Open: 19.52, Actual Close: 19.37, Signal: SELL, Return: 0.0077

Testing on 2022-03-31...

c:\file_struct\programs\python\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Predicted: 19.11, Previous Close: 19.37,Actual Open: 19.50, Actual Close: 19.10, Signal: SELL, Return: 0.0205

In [34]:
df_smoothed[df_smoothed.index >= pd.to_datetime('2022-01-03')]

ticker        HALO
timestamp
2022-01-03  40.370
2022-01-04  40.386
2022-01-05  39.978
2022-01-06  39.632
2022-01-07  39.048
...            ...
2022-03-25  37.842
2022-03-28  38.236
2022-03-29  38.774
2022-03-30  39.302
2022-03-31  39.534

[62 rows x 1 columns]